module POSTCODE
  PROVINCES = %i[ALAVA ALBACETE ALICANTE ALMERIA AVILA BADAJOZ BALEARES BARCELONA BURGOS CACERES
                 CADIZ CASTELLON CIUDADREAL CORDOBA CORUÑA CUENCA GERONA GRANADA GUADALAJARA GUIPUZCOA
                 HUELVA HUESCA JAEN LEON LERIDA RIOJA LUGO MADRID MALAGA MURCIA NAVARRA ORENSE ASTURIAS
                 PALENCIA PALMAS PONTEVEDRA SALAMANCA TENERIFE CANTABRIA SEGOVIA SEVILLA SORIA TARRAGONA
                 TERUEL TOLEDO VALENCIA VALLADOLID VIZCAYA ZAMORA ZARAGOZA CEUTA MELILLA].freeze
end
