# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1

# Define a job to be invoked later in a workflow.
jobs:
  tests:
    machine:
      - image: ubuntu-2004:202111-01
    steps:
      - checkout
      - run: docker run -t -v `pwd`:/app/test paula1999/tune-in

# Invoke jobs via workflows
workflows:
  ci:
    # Jobs to run
    jobs:
      - tests
